//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaz.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class distributionArz
    {
        public int id { get; set; }
        public int code { get; set; }
        public string name { get; set; }
        public decimal length { get; set; }
        public string status { get; set; }
        public string endpoint { get; set; }
    }
}
