//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaz.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class distributionArz
    {
        public int id { get; set; }
        public int code { get; set; }
        public string name { get; set; }
        public decimal length { get; set; }
        public string status { get; set; }
        public string endpoint { get; set; }
    }
}
