//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaz.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Description { get; set; }
        public int PipelineID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<bool> IsCritical { get; set; }
    
        public virtual User User { get; set; }
        public virtual Pipeline Pipeline { get; set; }
    }
}
