//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaz.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pipeline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pipeline()
        {
            this.Events = new HashSet<Event>();
            this.PipeLogs = new HashSet<PipeLog>();
        }
    
        public int PipelineID { get; set; }
        public int Code { get; set; }
        public string Location { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public System.DateTime LastInspectionDate { get; set; }
        public System.DateTime NextInspectionDate { get; set; }
        public int Status { get; set; }
        public decimal Pressure { get; set; }
        public decimal Length { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual PipeStatu PipeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PipeLog> PipeLogs { get; set; }
    }
}
