//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaz.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public int EmployeeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual User User { get; set; }
    }
}
